fifth commit via github actions

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -16,6 +16,15 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
 
+      - name: Check index.html exists
+        run: |
+            if [ ! -f index.html ]; then
+            echo "❌ index.html not found!"
+            exit 1
+            else
+            echo "✅ index.html exists"
+            fi
+
       - name: Configure Pages
         uses: actions/configure-pages@v5
 
